### PR TITLE
Runner

### PR DESCRIPTION
**Pull request by iain**
This is just the initial work I've done.

It maps repositories from a push notification to a directory, in which it tries to run some scripts.

This is a very rough draft, but it is a start.

This is how to do it:

```
curl -d "payload=`cat test/payload.json`" http://localhost:4567/github
```

Configuration is stored in repositories.yml

The worker keeps working but cannot be killed after one build, which is really odd.

Try it out, let's have a discussion. Add commits to this pull request.

### CODE REVIEW

**Comment by iain** [comment]
This is what I've done so far:
- Commits will be annotated when builds fail or succeed, they have lovely yellow blocks on github
- Pretty logging and error handling
- A way to handle failed builds and succeeded builds

On the handling of build results:

I've just implemented `script/failed` and `script/success`. If you're installing Mustacci, then you change these files yourself. This might remove the need of built in Campfire support. I'll extract the campfire notification to a separate gem from the Capistrano hooks.

What I still plan to do in this branch:
- Store the log somewhere
- Simplify the way payloads are communicated between the scripts. I'm thinking of storing the payload on disk and pass the filename around. A shared library will then be made for easy reading.

What do you guys think?

**Comment by marceldegraaf** [comment]
@iain regarding the Campfire notifications, what does this mean for the <tt>campfire</tt> branch?

**Comment by iain** [comment]
@marceldegraaf I don't think it's needed anymore. I'm extracting `blaze` from `capistrano-blaze` as we speak.

Do you agree?

**Comment by marceldegraaf** [comment]
Agreed. Should I remove the pull request and the branch?

**Comment by marceldegraaf** [comment]
@iain regarding storing the payload: why would you want that? What is missing or too complicated in the way the payload is being passed around now? Just curious :-).

**Comment by iain** [comment]
I just pass around 3 values of the payload. Any more would be a hassle, because I'm passing them around as command line parameters. I want every script to access more information, like the person who committed, etc.

**Comment by marceldegraaf** [comment]
Ah, right. Sounds reasonable to store it to disk, although we should pay attention to cleaning up stale files.

**Comment by marceldegraaf** [comment]
So, @iain, what needs to be done before this can be merged into master? Working on the layout is easier when the runner stuff is in place, so I can access the projects and build logs.

**Comment by iain** [comment]
I'll try to finish it up tonight

**Comment by marceldegraaf** [comment]
Nice! Let me know if you need help.

On Mon, Jun 18, 2012 at 2:54 PM, Iain Hecker <
reply@reply.github.com

**Pull request merged**
