### PR TITLE
Layout

### PR DESCRIPTION
**Pull request by marceldegraaf**
I've started working on a simple layout for the Sinatra app.
### Homepage

Offers a simple list of all projects currently known to Mustacci. It should at least have:
- The name of the project (duh)
- The status of the last build to see which projects are failing
- A link to the Github-repo
- A "Build now" button to start a new build
- A mustache icon (@dkln will work on that)

**Status**: prototyped
### Project detail page

Shows the details of a project. This includes:
- The name of the project
- A link to the Github repo
- Information about the last commit
- A larger graphic to show the status of the last build
- A detailed overview of the latest build, including console output (which may be hidden by default if the build succeeded)

**Status**: Started
### Build detail page

Shows the details of a build. This includes:
- Date and time of the build
- Status (success, failure, running)
- Console output from the build server (in case of a running build: streams new content to the bottom)

**Status**: Not started

---

This pull request is meant as a place for discussion. Let me know what you think!

### CODE REVIEW

**Comment by iain** [comment]
I would put the latest build with console output on the project information page. If a build failed, this is the only thing I'm interested in.

**Comment by marceldegraaf** [comment]
Good point. Let's do that for now. Later we could add an (initially hidden)
list of the other build below the latest build.

On Fri, Jun 15, 2012 at 11:42 AM, Iain Hecker <
reply@reply.github.com

**Comment by marceldegraaf** [comment]
Okay, so where are we now?
- Index page lists all projects. Status: **mockup**
- Project page shows project details. Status: **mockup**
- Project page receives runner console output through websocket. Status: **working**
- Build page displays build details. Status: **mockup**
- Build page displays build console output. Status: **working**

I'm considering adding SQLite to the project to store all available builds (and their status). Storing that on the file system will most likely become a bit messy because the data is relational.

Upon receiving a payload from an unknown project, Mustacci should simply add the project to its database and start building it.

**Comment by iain** [comment]
Looking at the DataMapper code, I don't like it. It's not you, it's DataMapper.

**Comment by marceldegraaf** [comment]
Yeah, I know. I don't like it either. Is there a better alternative?
Should we go for plain files after all?

On Jun 20, 2012, at 21:31, Iain Hecker
reply@reply.github.com
wrote:

**Comment by iain** [comment]
Thinking about it a bit more: a document database sounds ideal for this kind of thing: we could also store logs in it, for example.

If we're sticking to SQL, then ActiveRecord is better than DataMapper imho.

**Comment by marceldegraaf** [comment]
We could go for CouchDB. That would mean no migrations and we could
query the data store directly from the browser with Javascript. What
do you think?

On Jun 20, 2012, at 21:40, Iain Hecker
reply@reply.github.com
wrote:

**Comment by iain** [comment]
I like it :smile:

**Comment by marceldegraaf** [comment]
Alright, I'll throw the DataMapper stuff out and add CouchDB to the mix :-)

**Comment by marceldegraaf** [comment]
Latest status update on the layout:
- Index page lists all projects. Status: **done**
- Project page shows project details. Status: **done**
- Project page receives runner console output through websocket. Status: **done**
- Build page displays build details. Status: **done**
- Build page displays build console output. Status: **done**

CouchDB is used to persist all payloads, projects, builds and build outputs. I'll update the readme.

**Comment by iain** [comment]
We should merge this in, my gemification branch is getting too far out of sync otherwise.

**Comment by marceldegraaf** [comment]
Done!

**Pull request merged**
